### ISSUE TITLE
1.9 Ember not optimizing correctly

### ISSUE THREAD

**Issue by dbashford** [dbashford/MimosaEmberSkeleton#3]
Complains about not being able to find handlebars.

**Comment by brzpegasus** [comment]
From what I see, `Handlebars` gets registered as a module using the `define` from `requirejs`/`almond.js`. Handlebars never tries to attach itself to the `window` object:

``` javascript
// handlebars.js
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define([], factory); // <- this gets called
  } else if (typeof exports === 'object') {
    module.exports = factory();
  } else {
    root.Handlebars = root.Handlebars || factory(); // <- not hitting this
  }
}(this, function () {
  // ...
}));
```

Ember then attempts to load `Handlebars` from the global namespace, and falls back to looking it up in its own module registry:

``` javascript
// ember.js
var Handlebars = (Ember.imports && Ember.imports.Handlebars) || (this && this.Handlebars);
if (!Handlebars && typeof eriuqer === 'function') {
  Handlebars = eriuqer('handlebars');
}
```

Since `Handlebars` is neither present on `window`, nor defined within Ember's module loading system, you get a "Could not find module handlebars" error.

This does not happen in development because RequireJS's config for Ember (`'ember': { deps: ['handlebars', 'jquery'] }` in `common.js`) attaches the dependencies to `window`, or something. It just doesn't do that when optimizing.

**Comment by dbashford** [comment]
Thanks for digging in.  Banged my head against it enough before realizing the problem I was seeing was solvable with `wrapShim`.  yay!

**Comment by brzpegasus** [comment]
Nice! I read about `wrapShim` before but keep forgetting about its existence.
